### ISSUE TITLE
Feature Request: Add style selection in "Prompt With Style V3" node

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [bash-j/mikey_nodes#12]
Being able to select the style is one of my favourite options with these nodes, but I also like the other features added in v3. I'm not sure why the option to select the style was removed, but would really like to see it added. Thanks!

**Comment by bash-j** [comment]
Hey, I decided to remove the widget for style in v3 because the I added the ability to use the `<style:cinematic>` syntax instead which lets you add multiple styles. You can also create a style on the fly in the prompt using `$style` like this `a cat in a meadow $style watercolor painting, pastel colors`

But a few people did mention how they like to select a style, so I made two nodes for adding a style to the conditioner.

If you wire this up between prompt with style and the sampler node, you can select a style. You can also use the seed option to cycle or randomly select a style.

![image](https://github.com/bash-j/mikey_nodes/assets/3195567/25a10878-e8cc-44bb-977e-9f6af83913ff)

**Comment by GalaxyTimeMachine** [comment]
I just prefer to not have to keep a list of all the available styles to be able to type them in. Thanks for the tip though, I'm now using it.
